# NumPy Arrays

In [1]:
my_list=[1,2,3]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,11)#less than 11 i.e 10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,2) #start,end,step-size

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,5))#rows,columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,10)#start,end,no.of numbers in between them

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(4)#identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)#generates array of random values

array([0.97652229, 0.73623431, 0.94370785, 0.95385935, 0.86750717])

In [20]:
np.random.rand(5,5)#2D array

array([[0.26677308, 0.06184622, 0.61919314, 0.54944138, 0.59476854],
       [0.55318628, 0.65162125, 0.57067294, 0.48335365, 0.16030584],
       [0.22700575, 0.86798707, 0.06279652, 0.72548805, 0.70568811],
       [0.18820902, 0.3833217 , 0.87670807, 0.03897281, 0.53438401],
       [0.9365197 , 0.85825791, 0.27253051, 0.85920282, 0.10759467]])

In [21]:
np.random.randn(2)#generates random numbers from standard unifrom distribution

array([-1.55392092,  0.23473955])

In [22]:
np.random.randn(5,5)#2D array

array([[-0.1901971 , -0.26367923, -1.5919025 , -0.48458743,  0.47459975],
       [-0.5436947 ,  0.9864421 ,  0.19121043,  0.69878746, -0.68619614],
       [-0.64489964, -0.56692659,  0.85757454,  0.05108579,  0.17703427],
       [-0.8946942 , -0.23719182, -0.26979042, -1.42529198,  0.43729042],
       [ 2.28649569, -1.81115132,  0.91620126, -0.45420566, -0.67914189]])

In [24]:
np.random.randint(1,100)#generates random integer from 1 to 100

33

In [25]:
np.random.randint(1,100,10)#generates 10 random integers from 1 to 100

array([29, 87, 33, 32, 40, 90, 98, 77, 92, 55])

In [27]:
arr= np.arange(0,25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranar=np.random.randint(0,50,10)

In [30]:
ranar

array([ 5, 44, 14, 19, 47, 42,  3,  8, 31, 43])

In [31]:
arr.reshape(5,5)#reshaping 1D into 2D,NOTE:Elements should be equals to matrix size

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranar

array([ 5, 44, 14, 19, 47, 42,  3,  8, 31, 43])

In [33]:
ranar.min()

3

In [34]:
ranar.max()

47

In [35]:
ranar.argmax()# returns index of max element

4

In [36]:
ranar.argmin()# returns index of min element

6

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
arr.shape#telling that it is a 1d array

(25,)

In [39]:
lst=arr.reshape(5,5)#reshaping in 2D array and stores in lst

In [40]:
lst

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
arr.dtype#returns datatype

dtype('int32')

In [42]:
from numpy.random import randint

In [43]:
randint(2,10)

3

# NUmPy Indexing and Selection

In [44]:
import numpy as np

In [45]:
arr=np.arange(0,11)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[8]

8

In [48]:
arr[1:5]#returns values from strat(given) index to end(given) index

array([1, 2, 3, 4])

In [49]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [50]:
arr[:6]#0th index to 5th index

array([0, 1, 2, 3, 4, 5])

In [51]:
arr[5:]#5th index to end

array([ 5,  6,  7,  8,  9, 10])

In [52]:
arr=np.arange(0,11)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
slice_of_arr=arr[0:6]

In [55]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [56]:
slice_of_arr[:]=99

In [58]:
slice_of_arr #change not only occurs in slice array but also in original array

array([99, 99, 99, 99, 99, 99])

In [59]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
arr_copy=arr.copy()

In [61]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [62]:
arr_copy[:]=100#change oocured only in copy array

In [63]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [64]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [67]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [68]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
arr_2d[0][0]

5

In [70]:
arr_2d[0]#entire row

array([ 5, 10, 15])

In [71]:
arr_2d[1][1]

25

In [72]:
arr_2d[2][1]

40

In [73]:
arr_2d[1,2]#row,column

30

In [76]:
arr_2d[:2]#generates 0 & 1 row  

array([[ 5, 10, 15],
       [20, 25, 30]])

In [77]:
arr_2d[:2,1]#generates 0 & 1 row  

array([10, 25])

In [78]:
arr_2d[:2,1:]#generates start to 2(expect)  and 1 to end  

array([[10, 15],
       [25, 30]])

In [79]:
arr_2d[2:]  #2nd index i.e 3rd row to end

array([[35, 40, 45]])

In [81]:
arr_2d[0:1]  #2nd index i.e 3rd row to end

array([[ 5, 10, 15]])

In [82]:
arr=np.arange(1,11)

In [83]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
bool_arr=arr>5

In [85]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [86]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [87]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [88]:
arr[arr<3]

array([1, 2])

In [89]:
arr_2d=np.arange(0,50).reshape(5,10)

In [90]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [91]:
arr_2d[2:4]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [92]:
arr_2d[2,4:]

array([24, 25, 26, 27, 28, 29])

In [93]:
arr_2d[:2,4:]

array([[ 4,  5,  6,  7,  8,  9],
       [14, 15, 16, 17, 18, 19]])

In [95]:
arr_2d[2,3:]

array([23, 24, 25, 26, 27, 28, 29])

In [96]:
arr_2d[2,3:7]

array([23, 24, 25, 26])

#### NumPy OPerations 
1.Array with array
2.Array with Scalars
3.Universal Array Functions

In [97]:
import numpy as np

In [98]:
arr=np.arange(0,11)

In [99]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [101]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [102]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [103]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [104]:
arr*100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [105]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [106]:
arr/arr

C:\Users\syed usama ilyas\AppData\Local\Temp/ipykernel_7192/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [107]:
1/arr

C:\Users\syed usama ilyas\AppData\Local\Temp/ipykernel_7192/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [108]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [109]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [110]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [112]:
np.max(arr)

10

In [113]:
arr.max()

10

In [114]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])